config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("posts/", include("posts.urls")),
    path("users/", include("users.urls")),
    path("", index),
]

urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

posts/urls.py
from django.urls import path
from posts.views import feeds, comment_add, comment_delete, post_add, tags, post_detail

app_name = "posts"
urlpatterns = [
    path("feeds/", feeds, name="feeds"),
    path("comment_add/", comment_add, name="comment_add"),
    path("comment_delete/<int:comment_id>/", comment_delete, name="comment_delete"),
    path("post_add/", post_add, name="post_add"),
    path("tags/<str:tag_name>/", tags, name="tags"),
    path("<int:post_id>/", post_detail, name="post_detail"),
]

users/urls.py
from django.urls import path
from users.views import login_view, logout_view, signup

app_name = "users"
urlpatterns = [
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("signup/", signup, name="signup"),
]

templates/_base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <title>Pystagrams</title>
  {% block head %}{% endblock %}
</head>
<body>
  {% block base_content %}{% endblock %}
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'splide/splide.css' %}">
  <script src="{% static 'splide/splide.js' %}"></script>
</head>
<body>
  {% block content %}{% endblock %}
</body>
</html>

templates/base_nav.html
{% extends '_base.html' %}

{% block base_content %}
  {% include 'nav.html' %}
  {% block content %}{% endblock %}
{% endblock %}

templates/base_slider.html
{% extends '_base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'splide/splide.css' %}">
  <script src="{% static 'splide/splide.js' %}"></script>
{% endblock %}

{% block base_content %}
  {% include 'nav.html' %}
  {% block content %}
    <script>
      const elms = document.getElementsByClassName("splide")
      for (let i = 0; i < elms.length; i++) {
        new Splide(elms[i]).mount();
      }
    </script>
  {% endblock %}
{% endblock %}

templates/nav.html
<nav>
  <h1>
    <a href="{% url 'posts:feeds' %}">Pystagram</a>
  </h1>
  <a href="{% url 'posts:post_add' %}">Add post</a>
  <a href="{% url 'users:logout' %}">Logout</a>
</nav>